### PR TITLE
Issue 2809 fix

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**
fixes https://github.com/topcoder-platform/community-app/issues/2809

### CODE REVIEW

**Comment by PrakashDurlabhji** [comment]
@veshu @codeMinter can anyone please review this?

**Comment by sushilshinde** [comment]
@PrakashDurlabhji  @sexta13 wrong target branch

**Comment by sushilshinde** [comment]
Use https://github.com/topcoder-platform/topcoder-react-utils/tree/qa-accessibility

**Comment by PrakashDurlabhji** [comment]
@sushilshinde ready

**Comment by sexta13** [comment]
@PrakashDurlabhji , your commit messes with a lot of things and none of them seem like the clear filter/save filter focus problem. Can you please review?

**Comment by PrakashDurlabhji** [comment]
@sexta13 yes sure will raise new PR

**Pull request closed without merging**
