### PR TITLE
issue 2826 fixed

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**
This PR solves https://github.com/topcoder-platform/community-app/issues/2826.

As above issue depends on PrimaryButton  modification at \community-app\src\shared\components\challenge-detail\Header\index.jsx at line 339.

PrimaryButton is imported from topcoder-react-ui-kit.

And Primarybutton in topcoder-react-ui-kit is imported from topcoder-react-utils.

Hence raising PR here.

### CODE REVIEW

**Comment by PrakashDurlabhji** [comment]
@veshu @codeMinter can anyone please review this?

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Hey, can you share the your steps used to setup the `topcoder-react-utils`?

I'm getting error when try deploy this branch, I'm follow these steps:

community-app
- Checkout `qa-accessibility`
- `rimraf node_modules`
- `npm i`

topcoder-react-utils
- Checkout `qa-accessibility`
- `npm i`
- `npm run build:dev`

community-app
- `npm link ../topcoder-react-utils`
- `npm run build`
- Error in `topcoder-react-utils` missing package `react-redux-toastr`

topcoder-react-utils
- `npm i react-redux-toastr`
- `npm run build:dev`

community-app
- `npm link ../topcoder-react-utils`
- `npm run build`
- Error in `topcoder-react-utils` missing package `slick-carousel`

topcoder-react-utils
- `npm i slick-carousel`
- `npm run build:dev`

community-app
- `npm link ../topcoder-react-utils`
- `npm run build`
- Not showing a lot a missing packages:
  - `draft-js`
  - `rc-tooltip`
  - `react-dates`
  - `topcoder-react-ui-kit`
  - `highlight.js`

topcoder-react-utils
- `npm i draft-js rc-tooltip react-dates topcoder-react-ui-kit highlight.js`
- `npm run build:dev`

community-app
- `npm link ../topcoder-react-utils`
- `npm run build`
- Now I get this error:

image

**Comment by sushilshinde** [comment]
@PrakashDurlabhji  @sexta13 wrong target branch

**Comment by sushilshinde** [comment]
Use https://github.com/topcoder-platform/topcoder-react-utils/tree/qa-accessibility

**Pull request closed without merging**
