### PR TITLE
GenericLink add onKeyDown handler.

### PR DESCRIPTION
**Pull request by afrisalyp**
This commit is part of:
https://github.com/topcoder-platform/community-app/pull/2988
For issue:
https://github.com/topcoder-platform/community-app/issues/2909

### CODE REVIEW

**Comment by sexta13** [comment]
@afrisalyp missing prop types validation.

**Comment by afrisalyp** [comment]
@sexta13 Done.

**Comment by sushilshinde** [comment]
@afrisalyp  @sexta13 wrong target branch

**Comment by sushilshinde** [comment]
Use https://github.com/topcoder-platform/topcoder-react-utils/tree/qa-accessibility

**Comment by afrisalyp** [comment]
@sushilshinde Done.

A new PR submitted.
https://github.com/topcoder-platform/topcoder-react-utils/pull/45

**Pull request closed without merging**
