### PR TITLE
make id unique (https://github.com/topcoder-platform/community-app/issues/3095)

### PR DESCRIPTION
**Pull request by tc-mfikria**
issue: https://github.com/topcoder-platform/community-app/issues/3095
problem 1:  id of `<link data-chunk="chunkname" rel="stylesheet" id="tru-style">` is not unique so we need make id unique by change the id to `tru-style-chunkname`

### CODE REVIEW

**Comment by sushilshinde** [comment]
@tc-mfikria @sexta13 wrong target branch

**Comment by mfikria** [comment]
@sushilshinde what branch to use

**Comment by tc-mfikria** [comment]
@sushilshinde what branch to use

**Comment by sushilshinde** [comment]
Use https://github.com/topcoder-platform/topcoder-react-utils/tree/qa-accessibility

**Comment by tc-mfikria** [comment]
@sushilshinde updated

**Pull request merged**
