### PR TITLE
fix for unique id

### PR DESCRIPTION
**Pull request by anonymousjaggu**
changes for https://github.com/topcoder-platform/community-app/issues/2852

### CODE REVIEW

**Comment by sexta13** [comment]
https://github.com/topcoder-platform/topcoder-react-utils/pull/43 also fixes this...No need to merge this branch

**Comment by sushilshinde** [comment]
@anonymousjaggu  @sexta13 wrong target branch

**Comment by sushilshinde** [comment]
Use https://github.com/topcoder-platform/topcoder-react-utils/tree/qa-accessibility

**Comment by sexta13** [comment]
https://github.com/topcoder-platform/topcoder-react-utils/pull/43 fixes this

**Pull request closed without merging**
